---
title: "20191024_writing_functions"
author: "Jared Garfinkel"
date: "10/24/2019"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))

set.seed(1)
```

```{r}
sim_regression = function(n, beta0 = 2, beta1 = 3) {
  
  sim_data = tibble(
    x = rnorm(n, mean = 1, sd = 1),
    y = beta0 + beta1 * x + rnorm(n, 0, 1)
  )
  
  ls_fit = lm(y ~ x, data = sim_data)
  
  tibble(
    beta0_hat = coef(ls_fit)[1],
    beta1_hat = coef(ls_fit)[2]
  )
}
```

## Rerun using a for loop

```{r}
output = vector("list", length = 5000)

for (i in 1:5000) {
  output[[i]] = sim_regression(n = 30)
}

bind_rows(output) %>% 
  ggplot(aes(x = beta0_hat)) +
  geom_density()
```


## Rerun simulation using purrr

```{r}
output = rerun(5000, sim_regression(n=30))



bind_rows(output) %>% 
  ggplot(aes(x = beta0_hat)) +
  geom_density()
```

```{r}
output = bind_rows(output)

output %>% 
  ggplot(aes(x = beta0_hat, y = beta1_hat)) +
  geom_point()
```

try another sample size

```{r}
n_list = list("n_30"  = 30, 
              "n_60"  = 60, 
              "n_120" = 120, 
              "n_240" = 240)
output = vector("list", length = 4)

for (i in 1:4) {
  output[[i]] = rerun(100, sim_regression(n_list[[i]])) %>% 
    bind_rows()
}

output[[1]] %>% 
  ggplot(aes(x = beta0_hat)) +
  geom_density()
```

```{r}
sim_results = tibble(
  n = c(30, 60, 120, 240)
) %>% 
  mutate(
    output_list = map(.x = n, ~rerun(100, sim_regression(n = .x))),
    output_df = map(output_list, bind_rows)
  ) %>% 
  select(-output_list) %>% 
  unnest(output_df)
```

```{r}
sim_results %>% 
  group_by(n) %>% 
  summarize(var_b1 = var(beta1_hat))
```

```{r}
sim_results %>% 
  mutate(
    sample_size = str_c("n = ", n),
    sample_size = fct_reorder(sample_size, n)
  ) %>% 
  ggplot(aes(x= beta0_hat, y = beta1_hat)) +
  geom_point() +
  facet_grid(~sample_size)
```

